"""user model and refresh token

Revision ID: bef4a0594c74
Revises: 
Create Date: 2023-01-08 16:58:20.794730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef4a0594c74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer),
        sa.Column("first_name", sa.String(), nullable = False),
        sa.Column("last_name", sa.String(),nullable= False),
        sa.Column("email", sa.String, unique=True, nullable=False),
        sa.Column("password", sa.String, nullable= False),
        sa.Column("date_created", sa.TIMESTAMP(timezone=True),server_default = sa.text("now()")),
        sa.Column("date_updated", sa.TIMESTAMP(timezone=True),server_default= sa.text("now()")),
        sa.PrimaryKeyConstraint("id")
        
    )
    op.create_table(
        "user_refresh_token",
        sa.Column("id",sa.Integer),
        sa.Column("user_id", sa.Integer, nullable=False),
        sa.Column("token", sa.String, nullable= False),
         sa.Column("date_created", sa.TIMESTAMP(timezone=True),server_default= sa.text("now()")),
        sa.Column("date_updated", sa.TIMESTAMP(timezone=True),server_default= sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
            
        )
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_refresh_token_user_id_fkey", "user_refresh_token")
    op.drop_table("user_refresh_token")
    op.drop_table("users")
    pass
    # ### end Alembic commands ###
